// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "setpoint_t.h"

static int __setpoint_t_hash_computed;
static int64_t __setpoint_t_hash;

int64_t __setpoint_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __setpoint_t_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__setpoint_t_get_hash;
    (void) cp;

    int64_t hash = (int64_t)0x884b0b50e8cbf04eLL
         + __int64_t_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __setpoint_t_get_hash(void)
{
    if (!__setpoint_t_hash_computed) {
        __setpoint_t_hash = __setpoint_t_hash_recursive(NULL);
        __setpoint_t_hash_computed = 1;
    }

    return __setpoint_t_hash;
}

int __setpoint_t_encode_array(void *buf, int offset, int maxlen, const setpoint_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].utime), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].left_sp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].right_sp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].left_vel), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].right_vel), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int setpoint_t_encode(void *buf, int offset, int maxlen, const setpoint_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __setpoint_t_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __setpoint_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __setpoint_t_encoded_array_size(const setpoint_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int64_t_encoded_array_size(&(p[element].utime), 1);

        size += __float_encoded_array_size(&(p[element].left_sp), 1);

        size += __float_encoded_array_size(&(p[element].right_sp), 1);

        size += __float_encoded_array_size(&(p[element].left_vel), 1);

        size += __float_encoded_array_size(&(p[element].right_vel), 1);

    }
    return size;
}

int setpoint_t_encoded_size(const setpoint_t *p)
{
    return 8 + __setpoint_t_encoded_array_size(p, 1);
}

size_t setpoint_t_struct_size(void)
{
    return sizeof(setpoint_t);
}

int setpoint_t_num_fields(void)
{
    return 5;
}

int setpoint_t_get_field(const setpoint_t *p, int i, lcm_field_t *f)
{
    if (0 > i || i >= setpoint_t_num_fields())
        return 1;
    
    switch (i) {
    
        case 0: {
            f->name = "utime";
            f->type = LCM_FIELD_INT64_T;
            f->typestr = "int64_t";
            f->num_dim = 0;
            f->data = (void *) &p->utime;
            return 0;
        }
        
        case 1: {
            f->name = "left_sp";
            f->type = LCM_FIELD_FLOAT;
            f->typestr = "float";
            f->num_dim = 0;
            f->data = (void *) &p->left_sp;
            return 0;
        }
        
        case 2: {
            f->name = "right_sp";
            f->type = LCM_FIELD_FLOAT;
            f->typestr = "float";
            f->num_dim = 0;
            f->data = (void *) &p->right_sp;
            return 0;
        }
        
        case 3: {
            f->name = "left_vel";
            f->type = LCM_FIELD_FLOAT;
            f->typestr = "float";
            f->num_dim = 0;
            f->data = (void *) &p->left_vel;
            return 0;
        }
        
        case 4: {
            f->name = "right_vel";
            f->type = LCM_FIELD_FLOAT;
            f->typestr = "float";
            f->num_dim = 0;
            f->data = (void *) &p->right_vel;
            return 0;
        }
        
        default:
            return 1;
    }
}

const lcm_type_info_t *setpoint_t_get_type_info(void)
{
    static int init = 0;
    static lcm_type_info_t typeinfo;
    if (!init) {
        typeinfo.encode         = (lcm_encode_t) setpoint_t_encode;
        typeinfo.decode         = (lcm_decode_t) setpoint_t_decode;
        typeinfo.decode_cleanup = (lcm_decode_cleanup_t) setpoint_t_decode_cleanup;
        typeinfo.encoded_size   = (lcm_encoded_size_t) setpoint_t_encoded_size;
        typeinfo.struct_size    = (lcm_struct_size_t)  setpoint_t_struct_size;
        typeinfo.num_fields     = (lcm_num_fields_t) setpoint_t_num_fields;
        typeinfo.get_field      = (lcm_get_field_t) setpoint_t_get_field;
        typeinfo.get_hash       = (lcm_get_hash_t) __setpoint_t_get_hash;
    }
    
    return &typeinfo;
}
int __setpoint_t_decode_array(const void *buf, int offset, int maxlen, setpoint_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].utime), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].left_sp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].right_sp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].left_vel), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].right_vel), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __setpoint_t_decode_array_cleanup(setpoint_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_decode_array_cleanup(&(p[element].utime), 1);

        __float_decode_array_cleanup(&(p[element].left_sp), 1);

        __float_decode_array_cleanup(&(p[element].right_sp), 1);

        __float_decode_array_cleanup(&(p[element].left_vel), 1);

        __float_decode_array_cleanup(&(p[element].right_vel), 1);

    }
    return 0;
}

int setpoint_t_decode(const void *buf, int offset, int maxlen, setpoint_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __setpoint_t_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __setpoint_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int setpoint_t_decode_cleanup(setpoint_t *p)
{
    return __setpoint_t_decode_array_cleanup(p, 1);
}

int __setpoint_t_clone_array(const setpoint_t *p, setpoint_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_clone_array(&(p[element].utime), &(q[element].utime), 1);

        __float_clone_array(&(p[element].left_sp), &(q[element].left_sp), 1);

        __float_clone_array(&(p[element].right_sp), &(q[element].right_sp), 1);

        __float_clone_array(&(p[element].left_vel), &(q[element].left_vel), 1);

        __float_clone_array(&(p[element].right_vel), &(q[element].right_vel), 1);

    }
    return 0;
}

setpoint_t *setpoint_t_copy(const setpoint_t *p)
{
    setpoint_t *q = (setpoint_t*) malloc(sizeof(setpoint_t));
    __setpoint_t_clone_array(p, q, 1);
    return q;
}

void setpoint_t_destroy(setpoint_t *p)
{
    __setpoint_t_decode_array_cleanup(p, 1);
    free(p);
}

int setpoint_t_publish(lcm_t *lc, const char *channel, const setpoint_t *p)
{
      int max_data_size = setpoint_t_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = setpoint_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _setpoint_t_subscription_t {
    setpoint_t_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void setpoint_t_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    setpoint_t p;
    memset(&p, 0, sizeof(setpoint_t));
    status = setpoint_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding setpoint_t!!!\n", status);
        return;
    }

    setpoint_t_subscription_t *h = (setpoint_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    setpoint_t_decode_cleanup (&p);
}

setpoint_t_subscription_t* setpoint_t_subscribe (lcm_t *lcm,
                    const char *channel,
                    setpoint_t_handler_t f, void *userdata)
{
    setpoint_t_subscription_t *n = (setpoint_t_subscription_t*)
                       malloc(sizeof(setpoint_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 setpoint_t_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg setpoint_t LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int setpoint_t_subscription_set_queue_capacity (setpoint_t_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int setpoint_t_unsubscribe(lcm_t *lcm, setpoint_t_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe setpoint_t_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

